repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: check-json
          - id: end-of-file-fixer

    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
        - id: isort
          name: Sorting import statements
          args: ["--profile", "black"]

    - repo: https://github.com/pycqa/autoflake
      rev: v1.7.7
      hooks:
        - id: autoflake
          name: Remove unused variables and imports
          args: [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
          ]

    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
            name: Black Python code formatting

    - repo: https://github.com/myint/docformatter
      rev: v1.5.0
      hooks:
          - id: docformatter
            name: Format docstrings according to PEP 257
