version: "3.8"

services:

  user_personal_info:
    build:
      context: user_service
      dockerfile: ../Dockerfile
    command: gunicorn app.main:app --bind 0.0.0.0:8000
    volumes:
      - ./user_service/:/code/
    ports:
      - "8001:8000"
    env_file:
      - envs/.upi.env
    depends_on:
      - database

  event_info:
    build:
      context: event_service
      dockerfile: ../Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./event_service/:/code/
    ports:
      - "8002:8000"
    env_file:
      - envs/.ei.env
    depends_on:
      - database

  api_gateway:
    build:
      context: api_gateway
      dockerfile: ../Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./api_gateway/:/code/
    ports:
      - "8000:8000"
    env_file:
      - envs/.ag.env
    depends_on:
      - database

  database:
    image: postgres:15.1-alpine
    container_name: postgres
    restart: always
    env_file:
      - envs/.db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
