import os

JWT_SECRET_KEY = os.environ.get("JWT_SECRET_KEY")
JWT_REFRESH_SECRET_KEY = os.environ.get("JWT_REFRESH_SECRET_KEY")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = os.environ.get("ACCESS_TOKEN_EXPIRE_MINUTES")

EVENT_SERVICE_URL = os.environ.get("EVENT_SERVICE_URL")
USER_SERVICE_URL = os.environ.get("USER_SERVICE_URL")
